### ISSUE TITLE
Variable name changed

### ISSUE THREAD

**Issue by mattizem** [topepo/aml-london-2019#2]
There is a piece in Code.R which is not shown on the slides (the ggplot that makes /aml-london-2019-master/Part-3-Feature-Engineering.html#34 )
The code reads:
```
# Back to the Bivariate Example - Transformed Data (slide 34)
ggplot(inverse_test,      #I believe this is TYPO
```
Should be:
`ggplot(inverse_test_data,`

**Comment by topepo** [comment]
Thanks! Fixed in code
